[shared] No need to specify RuntimeError, it's the default exception type.
Avoids Ruby not being able to distinguish an exception from a function:
'NoMethodError Exception: undefined method `RuntimeError' for
<ActiveXML::Base:...>'